runtime: nodejs10
entrypoint: ./berglas exec --
handlers:
  - url: /_nuxt
    static_dir: .nuxt/dist/client

  - url: /(.*\.(gif|png|jpg|ico|txt))$
    static_files: static/\1
    upload: static/.*\.(gif|png|jpg|ico|txt)$

  - url: /sw.js
    static_files: static/sw.js
    upload: static/sw.js

  - url: /.*
    script: auto
    secure: always

env_variables:
  NUXT_HOST: '0.0.0.0'
  NUXT_PORT: '8080'
  FIREBASE_API_KEY: berglas://tm-secrets/FIREBASE_API_KEY
  FIREBASE_AUTH_DOMAIN: berglas://tm-secrets/FIREBASE_AUTH_DOMAIN
  FIREBASE_DATABASE_URL: berglas://tm-secrets/FIREBASE_DATABASE_URL
  FIREBASE_PROJECT_ID: berglas://tm-secrets/FIREBASE_PROJECT_ID
  FIREBASE_STORAGE_BUCKET: berglas://tm-secrets/FIREBASE_STORAGE_BUCKET
  FIREBASE_MESSAGING_SENDER_ID: berglas://tm-secrets/FIREBASE_MESSAGING_SENDER_ID
  FIREBASE_APP_ID: berglas://tm-secrets/FIREBASE_APP_ID
  FIREBASE_MEASUREMENT_ID: berglas://tm-secrets/FIREBASE_MEASUREMENT_ID
